<a href="https://colab.research.google.com/github/midhun-mid/Cyberbullying-Detection-using-Pre-Trained-BERT-Model/blob/midhun_patch_1/bert_cyberbullying_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!unzip "/content/dataset.zip"

Archive:  /content/dataset.zip
   creating: dataset/
   creating: dataset/train/
   creating: dataset/test/
   creating: dataset/train/sexism/
 extracting: dataset/train/sexism/sexism2924.txt  
  inflating: dataset/train/sexism/sexism2913.txt  
  inflating: dataset/train/sexism/sexism2911.txt  
  inflating: dataset/train/sexism/sexism2906.txt  
  inflating: dataset/train/sexism/sexism2894.txt  
 extracting: dataset/train/sexism/sexism2867.txt  
  inflating: dataset/train/sexism/sexism2860.txt  
 extracting: dataset/train/sexism/sexism2845.txt  
  inflating: dataset/train/sexism/sexism2844.txt  
 extracting: dataset/train/sexism/sexism2843.txt  
  inflating: dataset/train/sexism/sexism2842.txt  
  inflating: dataset/train/sexism/sexism2841.txt  
  inflating: dataset/train/sexism/sexism2838.txt  
  inflating: dataset/train/sexism/sexism2837.txt  
  inflating: dataset/train/sexism/sexism2833.txt  
 extracting: dataset/train/sexism/sexism2819.txt  
  inflating: dataset/train/sexism/sexism2

In [3]:
pip install ktrain

     |████████████████████████████████| 25.3MB 1.6MB/s 
     |████████████████████████████████| 6.8MB 33.7MB/s 
     |████████████████████████████████| 983kB 45.8MB/s 
     |████████████████████████████████| 266kB 43.1MB/s 
     |████████████████████████████████| 1.9MB 53.6MB/s 
     |████████████████████████████████| 1.2MB 51.8MB/s 
     |████████████████████████████████| 471kB 51.8MB/s 
     |████████████████████████████████| 3.3MB 34.2MB/s 
     |████████████████████████████████| 901kB 49.8MB/s 
  Created wheel for ktrain: filename=ktrain-0.26.3-cp37-none-any.whl size=25282390 sha256=02692c54d3653edda21d7da8fb37d5943d646e328b4ec51e743da51a39374949
  Stored in directory: /root/.cache/pip/wheels/16/05/be/d6e659b3349016b1059e19fa028f165af4eeae2c196f329112
  Created wheel for langdetect: filename=langdetect-1.0.9-cp37-none-any.whl size=993242 sha256=06c1d98739813355fc2cae7a3d15b0ce83c2f55474c60464428585f4ce736655
  Stored in directory: /root/.cache/pip/wheels/7e/18/13/038c34057808931c7d

In [ ]:
import os
import ktrain
from ktrain import text

In [ ]:
trn, val, preproc = text.texts_from_folder('dataset',maxlen=500,preprocess_mode='bert',train_test_names=['train', 'test'],classes=['none', 'racism', 'sexism'])

detected encoding: utf-8
downloading pretrained BERT model (uncased_L-12_H-768_A-12.zip)...
[██████████████████████████████████████████████████]
extracting pretrained BERT model...
done.

cleanup downloaded zip...
done.

preprocessing train...
language: en


Is Multi-Label? False
preprocessing test...
language: en


In [ ]:
trn

([array([[  101,  2045,  4854, ...,     0,     0,     0],
         [  101,   102,     0, ...,     0,     0,     0],
         [  101,  7025,  2006, ...,     0,     0,     0],
         ...,
         [  101, 10823,  2031, ...,     0,     0,     0],
         [  101, 19237,  2000, ...,     0,     0,     0],
         [  101,  1045,  2228, ...,     0,     0,     0]]),
  array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]])],
 array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        ...,
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.]], dtype=float32))

In [ ]:
val

([array([[  101,  2054,  2003, ...,     0,     0,     0],
         [  101, 13675, 23180, ...,     0,     0,     0],
         [  101,   102,     0, ...,     0,     0,     0],
         ...,
         [  101,  2339,  2003, ...,     0,     0,     0],
         [  101, 10645,  3791, ...,     0,     0,     0],
         [  101,  3057,  2064, ...,     0,     0,     0]]),
  array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]])],
 array([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.

In [ ]:
preproc

In [ ]:
model = text.text_classifier('bert', trn , preproc=preproc)

Is Multi-Label? False
maxlen is 500
done.


In [ ]:
learner = ktrain.get_learner(model,train_data=trn,val_data=val,batch_size=3)

In [ ]:
learner.fit_onecycle(1e-5,1)



begin training using onecycle policy with max lr of 1e-05...
1230/1230 [==============================] - 24526s 20s/step - loss: 0.6088 - accuracy: 0.7292 - val_loss: 0.4984 - val_accuracy: 0.8051


In [ ]:
predictor = ktrain.get_predictor(learner.model, preproc)

In [ ]:
predictor.save('/content/gdrive/MyDrive/model_BERT')


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/generic_utils.py:497: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  category=CustomMaskWarning)


In [ ]:
p = ktrain.load_predictor('model_BERT')


In [ ]:
data = [ 'Indian peoples are always a trouble maker'
         ]

In [ ]:
p.predict(data)

['racism']

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
model_save_name = 'tf_model.h5'
path = F"/content/gdrive/My Drive/{model_save_name}"
torch.save(model.state_dict(), path)


NameError: ignored

In [4]:
import ktrain
import pandas as pd
import re

In [5]:
p1 = ktrain.load_predictor('/content/gdrive/MyDrive/model_BERT')

In [ ]:
data = [ 'Indian peoples are always a trouble maker'
         ]

In [ ]:
print("The text is:",data,"Result:",p1.predict(data))

The text is: ['Indian peoples are always a trouble maker'] Result: ['racism']


In [ ]:
data=['If #Islam is so against idols that they smash Assyrian and Buddhists statues then why do they pray at Mecca and circumambulate the Kabba?']

In [ ]:
print("The text is:",data,"Result:",p1.predict(data))

The text is: ['If #Islam is so against idols that they smash Assyrian and Buddhists statues then why do they pray at Mecca and circumambulate the Kabba?'] Result: ['racism']


In [ ]:
data=['LOL  call me sexist. But i really hate girl gamer teams. really really hate. lol.']

In [ ]:
print("The text is:",data,"Result:",p1.predict(data))

The text is: ['LOL  call me sexist. But i really hate girl gamer teams. really really hate. lol.'] Result: ['sexism']


In [6]:
data=['Asia covers an area of 44,579,000 square kilometres, about 30 percentage of Earths total land area and 8 percentage of the Earths total surface area. The continent, which has long been home to the majority of the human population, was the site of many of the first civilizations.But asians are crazy,filthy and such a wimp.The border of Asia with Europe is a historical and cultural construct, as there is no clear physical and geographical separation between them. It is somewhat arbitrary and has moved since its first conception in classical antiquity. ']

Asia covers an area of 44,579,000 square kilometres, about 30 percentage of Earths total land area and 8 percentage of the Earths total surface area. The continent, which has long been home to the majority of the human population, was the site of many of the first civilizations.But asians are crazy,filthy and such a wimp.The border of Asia with Europe is a historical and cultural construct, as there is no clear physical and geographical separation between them. It is somewhat arbitrary and has moved since its first conception in classical antiquity.




output:


The text is: ['Asia covers an area of 44,579,000 square kilometres, about 30 percentage of Earths total land area and 8 percentage of the Earths total surface area. The continent, which has long been home to the majority of the human population, was the site of many of the first civilizations.But asians are crazy,filthy and such a wimp.The border of Asia with Europe is a historical and cultural construct, as there is no clear physical and geographical separation between them. It is somewhat arbitrary and has moved since its first conception in classical antiquity. '] Result: ['racism']


In [7]:
print("The text is:",data,"Result:",p1.predict(data))

The text is: ['Asia covers an area of 44,579,000 square kilometres, about 30 percentage of Earths total land area and 8 percentage of the Earths total surface area. The continent, which has long been home to the majority of the human population, was the site of many of the first civilizations.But asians are crazy,filthy and such a wimp.The border of Asia with Europe is a historical and cultural construct, as there is no clear physical and geographical separation between them. It is somewhat arbitrary and has moved since its first conception in classical antiquity. '] Result: ['racism']


In [8]:
data=['Which team do you think will be eliminated tonight? #MKR']

In [9]:
print("The text is:",data,"Result:",p1.predict(data))

The text is: ['Which team do you think will be eliminated tonight? #MKR'] Result: ['none']


In [10]:
data=['No he did not. After killing many he tuned it down to not killing those used for hunting and herding. Pets killed']

In [11]:
print("The text is:",data,"Result:",p1.predict(data))

The text is: ['No he did not. After killing many he tuned it down to not killing those used for hunting and herding. Pets killed'] Result: ['none']


In [12]:
data=['This show is going to air until Christmas isn''t it? ']

In [13]:
print("The text is:",data,"Result:",p1.predict(data))

The text is: ['This show is going to air until Christmas isnt it? '] Result: ['none']


In [14]:
data=['Given that Islam declared war on all humanity 1400 years ago why should we not burn down all Mosques?']
print("The text is:",data,"Result:",p1.predict(data))

The text is: ['Given that Islam declared war on all humanity 1400 years ago why should we not burn down all Mosques?'] Result: ['racism']


In [16]:
data=['JUST FELT THE NEED 2 EXPRESS THIS 4 SOME REASON  Dont get me wrong Iam not sexist but seeing female engineers on site is weird']
print("The text is:",data,"Result:",p1.predict(data))

The text is: ['JUST FELT THE NEED 2 EXPRESS THIS 4 SOME REASON  Dont get me wrong Iam not sexist but seeing female engineers on site is weird'] Result: ['sexism']
